const FRIENDS = {
  ON_REQUEST_ALL: 'ON_REQUEST_ALL',
  ON_REQUEST_ALL_SUCCESS: 'ON_REQUEST_ALL_SUCCESS',
  ON_REQUEST_ALL_FAILED: 'ON_REQUEST_ALL_FAILED',
  ON_SET_NEW_FRIEND_DIALOG: 'ON_SET_NEW_FRIEND_DIALOG',
  ON_SET_FRIEND_TO_ATTACH: 'ON_SET_FRIEND_TO_ATTACH',
  ON_SAVE_NEW_FRIEND: 'ON_SAVE_NEW_FRIEND',
  ON_SAVE_NEW_FRIEND_SUCCESS: 'ON_SAVE_NEW_FRIEND_SUCCESS',
  ON_SAVE_NEW_FRIEND_FAILED: 'ON_SAVE_NEW_FRIEND_FAILED',
};

export { FRIENDS };
